// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdF4u-jmydb6hHsqahwaAWKaAFj6TpM1U',
    appId: '1:19410684722:web:55bc090269b76f9f04a52b',
    messagingSenderId: '19410684722',
    projectId: 'shagaf-fe682',
    authDomain: 'shagaf-fe682.firebaseapp.com',
    databaseURL: 'https://shagaf-fe682-default-rtdb.firebaseio.com',
    storageBucket: 'shagaf-fe682.firebasestorage.app',
    measurementId: 'G-49G8XWZ4Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZjXmZqqZWM7WgdaTpi4V2ne159kZjc8',
    appId: '1:19410684722:android:a0f6e6edcf89183404a52b',
    messagingSenderId: '19410684722',
    projectId: 'shagaf-fe682',
    databaseURL: 'https://shagaf-fe682-default-rtdb.firebaseio.com',
    storageBucket: 'shagaf-fe682.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqqcNsFEQw6bG6dwEGMCCyP918ScqdHU0',
    appId: '1:19410684722:ios:1ab612686f71257204a52b',
    messagingSenderId: '19410684722',
    projectId: 'shagaf-fe682',
    databaseURL: 'https://shagaf-fe682-default-rtdb.firebaseio.com',
    storageBucket: 'shagaf-fe682.firebasestorage.app',
    iosClientId: '19410684722-3kok1g6kls02tn4od2rvelnhjnvf2ncc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shagf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqqcNsFEQw6bG6dwEGMCCyP918ScqdHU0',
    appId: '1:19410684722:ios:1ab612686f71257204a52b',
    messagingSenderId: '19410684722',
    projectId: 'shagaf-fe682',
    databaseURL: 'https://shagaf-fe682-default-rtdb.firebaseio.com',
    storageBucket: 'shagaf-fe682.firebasestorage.app',
    iosClientId: '19410684722-3kok1g6kls02tn4od2rvelnhjnvf2ncc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shagf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdF4u-jmydb6hHsqahwaAWKaAFj6TpM1U',
    appId: '1:19410684722:web:55bc090269b76f9f04a52b',
    messagingSenderId: '19410684722',
    projectId: 'shagaf-fe682',
    authDomain: 'shagaf-fe682.firebaseapp.com',
    databaseURL: 'https://shagaf-fe682-default-rtdb.firebaseio.com',
    storageBucket: 'shagaf-fe682.firebasestorage.app',
    measurementId: 'G-49G8XWZ4Z7',
  );

}