// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmvsMOmOemvGMJ36PgFaAmgmrkjj5E_1c',
    appId: '1:404377602470:web:102f7c3754a25cd9bd2767',
    messagingSenderId: '404377602470',
    projectId: 'shaghaf-cb396',
    authDomain: 'shaghaf-cb396.firebaseapp.com',
    storageBucket: 'shaghaf-cb396.firebasestorage.app',
    measurementId: 'G-1NKG8WWNLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2MTW4qGpKoB2SCRxBpmDihE3TuzbYO1M',
    appId: '1:404377602470:android:369ccae3c39ac89abd2767',
    messagingSenderId: '404377602470',
    projectId: 'shaghaf-cb396',
    storageBucket: 'shaghaf-cb396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMIYExRcW6dQqrhXKf4Vhn9nfZQpJbCWc',
    appId: '1:404377602470:ios:c975dcb1d0595b3dbd2767',
    messagingSenderId: '404377602470',
    projectId: 'shaghaf-cb396',
    storageBucket: 'shaghaf-cb396.firebasestorage.app',
    androidClientId: '404377602470-o46r8f5t62u0pekdr6302etfcriof8hl.apps.googleusercontent.com',
    iosClientId: '404377602470-q1jte6h0oc9gsee3cej1374e6cc2lpdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shagf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMIYExRcW6dQqrhXKf4Vhn9nfZQpJbCWc',
    appId: '1:404377602470:ios:c975dcb1d0595b3dbd2767',
    messagingSenderId: '404377602470',
    projectId: 'shaghaf-cb396',
    storageBucket: 'shaghaf-cb396.firebasestorage.app',
    androidClientId: '404377602470-o46r8f5t62u0pekdr6302etfcriof8hl.apps.googleusercontent.com',
    iosClientId: '404377602470-q1jte6h0oc9gsee3cej1374e6cc2lpdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shagf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmvsMOmOemvGMJ36PgFaAmgmrkjj5E_1c',
    appId: '1:404377602470:web:2d92c547679c3186bd2767',
    messagingSenderId: '404377602470',
    projectId: 'shaghaf-cb396',
    authDomain: 'shaghaf-cb396.firebaseapp.com',
    storageBucket: 'shaghaf-cb396.firebasestorage.app',
    measurementId: 'G-WHMKXN7H3F',
  );
}
